"""
Pydantic models for structured query validation.
These schemas validate the JSON output from Gemini before Pandas execution.
"""

from __future__ import annotations

from pydantic import BaseModel, Field, field_validator
from typing import Optional


class QueryFilters(BaseModel):
    """Filters to apply to the dataset before aggregation."""
    city: Optional[str | list[str]] = None
    state: Optional[str | list[str]] = None
    weather: Optional[str | list[str]] = None
    road_type: Optional[str | list[str]] = None
    cause: Optional[str | list[str]] = None
    accident_severity: Optional[str | list[str]] = None
    visibility: Optional[str | list[str]] = None
    traffic_density: Optional[str | list[str]] = None
    day_of_week: Optional[str | list[str]] = None
    is_weekend: Optional[int] = None
    is_peak_hour: Optional[int] = None
    traffic_signal: Optional[int] = None
    festival: Optional[str | list[str]] = None
    hour: Optional[int | list[int]] = None
    year: Optional[int | list[int]] = None
    month: Optional[int | list[int]] = None


class StructuredQuery(BaseModel):
    """The structured JSON query generated by the LLM."""
    intent: str = Field(
        ...,
        description="Query intent type: aggregate, compare, trend, top_n, distribution, filter, out_of_scope"
    )
    metric: Optional[str] = Field(
        default="accident_id",
        description="The column to measure (e.g. casualties, risk_score, accident_id)"
    )
    group_by: Optional[str | list[str]] = Field(
        default=None,
        description="Column(s) to group results by"
    )
    aggregation: Optional[str] = Field(
        default="count",
        description="Aggregation function: count, sum, mean, min, max"
    )
    filters: Optional[QueryFilters] = Field(
        default=None,
        description="Filters to narrow down the dataset"
    )
    top_n: Optional[int] = Field(
        default=None,
        description="Number of top results to return (for top_n intent)",
        ge=1,
        le=20,
    )
    sort_order: Optional[str] = Field(
        default="desc",
        description="Sort order: asc or desc"
    )
    compare_values: Optional[list[str]] = Field(
        default=None,
        description="Values to compare (e.g. ['Delhi', 'Mumbai'] for city comparison)"
    )
    compare_column: Optional[str] = Field(
        default=None,
        description="Column containing the compare_values"
    )
    time_column: Optional[str] = Field(
        default=None,
        description="Time granularity for trends: month, year, day_of_week, hour"
    )
    reason: Optional[str] = Field(
        default=None,
        description="Reason for out_of_scope classification"
    )

    @field_validator("intent")
    @classmethod
    def validate_intent(cls, v: str) -> str:
        allowed = ["aggregate", "compare", "trend", "top_n", "distribution", "filter", "out_of_scope"]
        if v not in allowed:
            raise ValueError(f"Intent '{v}' is not allowed. Must be one of: {allowed}")
        return v

    @field_validator("aggregation")
    @classmethod
    def validate_aggregation(cls, v: str | None) -> str | None:
        if v is None:
            return "count"
        allowed = ["count", "sum", "mean", "min", "max"]
        if v not in allowed:
            raise ValueError(f"Aggregation '{v}' not allowed. Must be one of: {allowed}")
        return v

    @field_validator("sort_order")
    @classmethod
    def validate_sort_order(cls, v: str | None) -> str | None:
        if v is None:
            return "desc"
        if v not in ("asc", "desc"):
            raise ValueError("sort_order must be 'asc' or 'desc'")
        return v


class UserQueryRequest(BaseModel):
    """Incoming request from the API endpoint."""
    question: str = Field(
        ...,
        min_length=3,
        max_length=500,
        description="The natural language question about road accident data"
    )
